/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author isata
 */
public class TelaAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reservas = new javax.swing.JButton();
        historico = new javax.swing.JButton();
        disponivelBreve = new javax.swing.JButton();
        configConta = new javax.swing.JLabel();
        livrosDisponiveis = new javax.swing.JButton();
        NomesSobrenome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        reservas.setBackground(new java.awt.Color(51, 75, 210));
        reservas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reservas.setForeground(new java.awt.Color(255, 255, 255));
        reservas.setText("Disponíveis em breve");
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        getContentPane().add(reservas);
        reservas.setBounds(410, 250, 150, 90);

        historico.setBackground(new java.awt.Color(255, 153, 51));
        historico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        historico.setForeground(new java.awt.Color(255, 255, 255));
        historico.setText("Meu histórico");
        historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoActionPerformed(evt);
            }
        });
        getContentPane().add(historico);
        historico.setBounds(610, 250, 150, 90);

        disponivelBreve.setBackground(new java.awt.Color(51, 75, 210));
        disponivelBreve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        disponivelBreve.setForeground(new java.awt.Color(255, 255, 255));
        disponivelBreve.setText("Minhas Reservas");
        disponivelBreve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponivelBreveActionPerformed(evt);
            }
        });
        getContentPane().add(disponivelBreve);
        disponivelBreve.setBounds(30, 250, 150, 90);

        configConta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        configConta.setForeground(new java.awt.Color(51, 51, 255));
        configConta.setText("Configurações de conta");
        getContentPane().add(configConta);
        configConta.setBounds(550, 140, 230, 50);

        livrosDisponiveis.setBackground(new java.awt.Color(255, 153, 51));
        livrosDisponiveis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        livrosDisponiveis.setForeground(new java.awt.Color(255, 255, 255));
        livrosDisponiveis.setText("Livros Disponíveis");
        livrosDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosDisponiveisActionPerformed(evt);
            }
        });
        getContentPane().add(livrosDisponiveis);
        livrosDisponiveis.setBounds(220, 250, 150, 90);

        NomesSobrenome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NomesSobrenome.setForeground(new java.awt.Color(255, 153, 51));
        NomesSobrenome.setText("Nome e sobrenome");
        getContentPane().add(NomesSobrenome);
        NomesSobrenome.setBounds(100, 150, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Tela Aluno.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservasActionPerformed

    private void livrosDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosDisponiveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_livrosDisponiveisActionPerformed

    private void disponivelBreveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponivelBreveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disponivelBreveActionPerformed

    private void historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAluno telaAluno = new TelaAluno();
                telaAluno.setSize(800, 600);
                telaAluno.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomesSobrenome;
    private javax.swing.JLabel configConta;
    private javax.swing.JButton disponivelBreve;
    private javax.swing.JButton historico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton livrosDisponiveis;
    private javax.swing.JButton reservas;
    // End of variables declaration//GEN-END:variables
}
