/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UsuarioController;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author steph
 */
public class TelaCadastro extends javax.swing.JFrame {
    private final UsuarioController user;

    /**
     * Creates new form Cadastro
     */
    public TelaCadastro() {
        initComponents();
        this.user = new UsuarioController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        emailc = new javax.swing.JTextField();
        senhac = new javax.swing.JPasswordField();
        senhaco = new javax.swing.JPasswordField();
        nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelar.setContentAreaFilled(false);
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 90, 30));

        cadastrar.setBackground(new java.awt.Color(255, 153, 0));
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setContentAreaFilled(false);
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 90, 30));

        emailc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        emailc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailcActionPerformed(evt);
            }
        });
        getContentPane().add(emailc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 270, 20));

        senhac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(senhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 270, -1));

        senhaco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(senhaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 270, -1));

        nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 270, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Cadastro (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 402, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void emailcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailcActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        try {
            String nomeTela = getNome().getText();
            String emailTela = getEmailc().getText().toLowerCase();
            String senhaTela = String.valueOf(senhac.getPassword());
            String confirmaSenha = String.valueOf(senhaco.getPassword());
            
            if(nomeTela != null && emailTela != null && senhaTela != null && confirmaSenha != null)
                if(user.validaEmail(emailTela)){
                    if(user.verificaSenha(senhaTela, confirmaSenha)){
                        if(user.validaSenha(senhaTela)){
                            if(user.adicionar(user.criarUsuario(nomeTela, emailTela, senhaTela, confirmaSenha))){
                                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
                                dispose();
                            }else{ 
                                JOptionPane.showMessageDialog(null, "Não foi possível realizar ");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "A senha deve conter 8 digitos entre números, letras maiúsculas e minusculas e caracteres especiais");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "As senhas não conferem");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Favor fonecer um e-mail institucional do Senac");
                } 
        }catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Favor preencher todos os campos");
            }
 
        
    
    }//GEN-LAST:event_cadastrarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadastro telaCadastro = new TelaCadastro();
                telaCadastro.setSize(399, 400);
                telaCadastro.setVisible(true);
            }
        });
    }

    public JTextField getEmailc() {
        return emailc;
    }

    public void setEmailc(JTextField emailc) {
        this.emailc = emailc;
    }

    public JTextField getNome() {
        return nome;
    }

    public void setNome(JTextField nome) {
        this.nome = nome;
    }

    public JPasswordField getSenhac() {
        return senhac;
    }

    public void setSenhac(JPasswordField senhac) {
        this.senhac = senhac;
    }

    public JPasswordField getSenhaco() {
        return senhaco;
    }

    public void setSenhaco(JPasswordField senhaco) {
        this.senhaco = senhaco;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField emailc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senhac;
    private javax.swing.JPasswordField senhaco;
    // End of variables declaration//GEN-END:variables
}
