/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JLabel;

/**
 *
 * @author isata
 */
public class TelaDisponiveis extends javax.swing.JFrame {

    /**
     * Creates new form TelaDisponiveis
     */
    public TelaDisponiveis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltar = new javax.swing.JButton();
        reservasLivros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        livrosDisponiveis = new javax.swing.JButton();
        reservas = new javax.swing.JButton();
        nomeJLabel = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        configConta = new javax.swing.JButton();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltar.setContentAreaFilled(false);
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 473, 150, 40));

        reservasLivros.setContentAreaFilled(false);
        reservasLivros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservasLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasLivrosActionPerformed(evt);
            }
        });
        getContentPane().add(reservasLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 150, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Autor", "Quantidade de exemplares"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 190));

        livrosDisponiveis.setContentAreaFilled(false);
        livrosDisponiveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        livrosDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosDisponiveisActionPerformed(evt);
            }
        });
        getContentPane().add(livrosDisponiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 150, 90));

        reservas.setContentAreaFilled(false);
        reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservasActionPerformed(evt);
            }
        });
        getContentPane().add(reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 90));

        nomeJLabel.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        getContentPane().add(nomeJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 300, 30));

        sair.setBackground(new java.awt.Color(255, 204, 153));
        sair.setForeground(new java.awt.Color(255, 255, 255));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 60, 20));

        configConta.setContentAreaFilled(false);
        configConta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configContaActionPerformed(evt);
            }
        });
        getContentPane().add(configConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 190, 20));

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Tela Aluno - tabela disponíveis.png"))); // NOI18N
        getContentPane().add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void configContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configContaActionPerformed

    private void reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasActionPerformed
        TelaReservas telaReservas = new TelaReservas();
        telaReservas.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_reservasActionPerformed

    private void livrosDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosDisponiveisActionPerformed
        TelaDisponiveis telaDisponiveis = new TelaDisponiveis();
        telaDisponiveis.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_livrosDisponiveisActionPerformed

    private void reservasLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservasLivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservasLivrosActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        TelaAluno telaAluno = new TelaAluno();
        telaAluno.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDisponiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDisponiveis telaDisponiveis = new TelaDisponiveis();
                telaDisponiveis.setSize(810, 800);
                telaDisponiveis.setVisible(true);
            }
        });
    }
public JLabel getNomeJLabel() {
        return nomeJLabel;
    }

    public void setNomeJLabel(JLabel nomeJLabel) {
        this.nomeJLabel = nomeJLabel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configConta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JButton livrosDisponiveis;
    private javax.swing.JLabel nomeJLabel;
    private javax.swing.JButton reservas;
    private javax.swing.JButton reservasLivros;
    private javax.swing.JButton sair;
    private javax.swing.JTable table;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
